include: package:lints/recommended.yaml

analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    - always_declare_return_types
    - avoid_dynamic_calls
    - directives_ordering
    - prefer_single_quotes
